// packages/components/react/button/button.tsx
import React from 'react'
import { Slot } from '@radix-ui/react-slot'
import type { VariantProps } from '@openui-org/theme'
import { button, cn } from '@openui-org/theme'

export interface Props extends React.ButtonHTMLAttributes<HTMLButtonElement>,
  VariantProps<typeof button> {
  asChild?: boolean
}

interface Comp extends HTMLButtonElement {}

const Button = React.forwardRef<Comp, Props>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button'
    return (
      <Comp
        className={cn(button({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  },
)

Button.displayName = 'Button'

export default Button

// packages/components/vue/button/button.vue
<script setup lang="ts">
import { button, cn } from '@openui-org/theme'

interface Props {
  variant?: NonNullable<Parameters<typeof button>[0]>['variant']
  size?: NonNullable<Parameters<typeof button>[0]>['size']
  as?: string
}

withDefaults(defineProps<Props>(), {
  as: 'button',
})
</script>

<template>
  <component
    :is="as"
    :class="cn(button({ variant, size }), $attrs.class ?? '')"
  >
    <slot />
  </component>
</template>
