// packages/components/vue/accordion/accordion-trigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import type { AccordionTriggerProps } from 'radix-vue'
import { computed } from 'vue'
import { AccordionHeader, AccordionTrigger } from 'radix-vue'

import { accordionTrigger, cn } from '@openui-org/theme'

const props = defineProps<AccordionTriggerProps & { class?: HTMLAttributes['class'] }>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props

  return delegated
})
</script>

<template>
  <AccordionHeader class="flex">
    <AccordionTrigger
      v-bind="delegatedProps"
      :class="cn(accordionTrigger(), props.class)"
    >
      <slot />
      <slot name="icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down h-4 w-4 shrink-0 transition-transform duration-200"><path d="m6 9 6 6 6-6" /></svg>
      </slot>
    </AccordionTrigger>
  </AccordionHeader>
</template>

// packages/components/react/accordion/accordion-trigger.tsx
import * as React from 'react'
import * as AccordionPrimitive from '@radix-ui/react-accordion'
import { accordionTrigger, cn } from '@openui-org/theme'

export interface Comp extends React.ElementRef<typeof AccordionPrimitive.Trigger> {}
export interface Props extends React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Trigger> {}

const AccordionTrigger = React.forwardRef<Comp, Props>(({ className, children, ...props }, ref) => {
  return (
    <AccordionPrimitive.Header className="flex">
      <AccordionPrimitive.Trigger
        ref={ref}
        className={cn(accordionTrigger(), className)}
        {...props}
      >
        {children}
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-chevron-down h-4 w-4 shrink-0 transition-transform duration-200"><path d="m6 9 6 6 6-6" /></svg>
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  )
})

AccordionTrigger.displayName = AccordionPrimitive.Trigger.displayName

export default AccordionTrigger
